PIC_PINS = {
    'PIC_RESET_ROW_N'   : ('G', 1), 
    'PIC_RESET_COL_N'   : ('G', 0),
    'PIC_RESET_GLOBAL_N': ('E', 6),
    'PIC_STROBE_REG_N'  : ('B', 8),
    'PIC_RESET_DELAY_N' : ('B', 7),
    'PIC_ASSERT_COL'    : ('G', 12),
    'PIC_ASSERT_ND'     : ('G', 13),
    'PIC_ASSERT_REGS'   : ('G', 7),
    'PIC_ASSERT_CD'     : ('E', 0),
    'PIC_ASSERT_ML'     : ('F', 1),
    'PIC_ASSERT_WL'     : ('B', 11),
    'PIC_TCAM_TIA_SH_STRB'  : ('G', 8),
    'PIC_PC'            : ('B', 10),
    'DAC_LDAC_N'        : ('D', 0),
    'DAC_TGP'           : ('D', 12),
    'DAC_CLR_N'         : ('D', 9),
    'ADC_CONVST'        : ('E', 1),
    'ADC_EOC_N'         : ('A', 14),
    'ADC_CS_N'          : ('A', 9),
    'PIC_SA_LATCH'      : ('E', 7),
    'PIC_TRIGGER'       : ('E', 4),
    # TEMP
    'ADC_RD_N'          : ('K', 2),
    'ADC_WR_N'          : ('K', 1),
}

DAC_CH = {
    'PLANE_VPP': 0,
    'DAC_VREF_ARRAY': 1,
    'P_VREF_TIA': 2,
    'DAC_VREF_HI_CMP': 3,
    'P_VREF_SH': 4,
    'DAC_VP_PAD': 5,
    'P_TVDD': 6,
    'P_VAGC_L': 7,
    'P_AGC_R': 8,
    'P_ADC_EXT_TEST_IN': 9,
    'P_AMP_VREF': 10,
    'P_AMP_INPUT': 11,
    'DAC_SPARE1': 12,
    'DAC_SPARE2': 13,
    'DAC_DRIVE_VN': 14,
    'DAC_SCHOTTKY': 15,
}
