PIC_PINS = {
    'COL_ROW_SEL': ('F', 12),
    'ADC_OUT<1>': ('A', 1),
    'COL_WRITE_CONNECT': ('F', 13),
    'ADC_OUT<0>': ('A', 0),
    'PIC_ADC_0': ('B', 0),
    'DPE_INTERNAL_EN': ('B', 7),
    'PIC_ADC_1': ('B', 1),
    'PIC_ADC_7': ('B', 6),
    'PIC_LDAC': ('D', 0),
    'UPDATE_TIA_CONF': ('C', 13),
    'NFORCE_SAFE1': ('G', 13),
    'DPE_PULSE': ('G', 12),
    'PIC_SDI': ('D', 4),
    'ADC_OUT<8>': ('G', 14),
    'PIC_SDO': ('D', 5),
    'ADC_OUT<7>': ('A', 7),
    'ADC_OUT<9>': ('G', 15),
    'ADC_OUT<6>': ('A', 6),
    'ROW_COL_DATA<15>': ('J', 15),
    'ROW_COL_BANK<1>': ('K', 1),
    'PIC_SHORT_VREF_ARRAY': ('G', 9),
    'ROW_COL_BANK<2>': ('K', 2),
    'ARRAY_EN<2>': ('H', 7),
    'ADC_OUT<5>': ('A', 5),
    'DPE_EXT_PULSE': ('C', 1),
    'NFORCE_SAFE0': ('B', 9),
    'PICI2C_SDA': ('F', 5),
    'CONNECT_TIA': ('F', 4),
    'PIC_ADC_3': ('B', 8),
    'ROW_COL_DATA<14>': ('J', 14),
    'DPE_EXT_SH': ('C', 2),
    'ROW_COL_DATA<13>': ('J', 13),
    'ADC_OUT<4>': ('A', 4),
    'PIC_CLR': ('D', 9),
    'ROW_COL_BANK<0>': ('K', 0),
    'ADC_OUT<12>': ('H', 2),
    'ROW_COL_BANK<3>': ('K', 3),
    'ARRAY_EN<0>': ('H', 3),
    'ADC_FIFO_EN<0>': ('K', 4),
    'ADC_FIFO_EN<1>': ('K', 5),
    'SERIAL_CHAIN_SEL0': ('C', 3),
    'ADC_FIFO_EN<2>': ('K', 6),
    'ROW_COL_DATA<8>': ('J', 4),
    'ADC_FIFO_EN<3>': ('K', 7),
    'ROW_COL_DATA<9>': ('J', 5),
    'ROW_COL_DATA<7>': ('J', 3),
    'ROW_COL_DATA<10>': ('J', 6),
    'ROW_COL_DATA<4>': ('H', 15),
    'ROW_COL_DATA<11>': ('J', 7),
    'ROW_COL_DATA<12>': ('J', 12),
    'ADC_OUT<3>': ('A', 3),
    'ROW_COL_DATA<2>': ('H', 11),
    'ROW_COL_DATA<6>': ('J', 2),
    'ADC_SEL_EXTERNAL': ('G', 7),
    'WRITE_ADD_CAP': ('B', 15),
    'ROW_WRITE_CONNECT': ('G', 8),
    'ARRAY_EN<1>': ('H', 6),
    'WRITE_FWD': ('E', 8),
    'PIC_CS': ('D', 14),
    'WRITE_SEL_EXT': ('E', 9),
    'PIC_SCK': ('D', 15),
    'PIC_ADC_4': ('B', 4),
    'PIC_TGP': ('F', 2),
    'PIC_ADC_6': ('B', 3),
    'PIC_SHORT_VREF_HI_CMP': ('F', 8),
    'PIC_ADC_2': ('B', 2),
    'ROW_COL_DATA<0>': ('H', 9),
    'PWR_GOOD': ('A', 9),
    'ROW_COL_DATA<1>': ('H', 10),
    'READ_BIT': ('A', 10),
    'ADC_OUT<2>': ('A', 2),
    'ADC_OUT<10>': ('H', 0),
    'DPE_EXT_OVERRIDE_EN': ('D', 10),
    'ADC_OUT<11>': ('H', 1),
    'ROW_COL_DATA<3>': ('H', 12),
    'WRT_INTERNAL_EN': ('B', 10),
    'SERIAL_CK_IN': ('D', 1),
    'AGC_INTERNAL_EN': ('B', 11),
    'ROW_COL_DATA<5>': ('J', 0),
    'READ_DPE': ('A', 14),
    'CONNECT_COLUMN_T': ('A', 15),
    'SERIAL_BUS_IN': ('D', 3),
    'PIC_ADC_5': ('E', 4),
    'ADC_CK': ('E', 3),
    'NFORCE_SAFE2': ('E', 2),
    'CK_ARRAY': ('F', 0),
    'WRT_PULSE': ('E', 1),
    'PICI2C_SCL': ('D', 12),
    'AGC_PULSE': ('E', 0),
    'NRESET_DPE_ENGINE': ('D', 13),
    'SERIAL_BUS_OUT': ('D', 2),
    'AMP_EN': ('F', 1),
    'ADC_DONE': ('G', 1),
    'SERIAL_CLK_OUT': ('E', 5),
    'ADC_FIFO_ADVANCE': ('G', 0),
    'NRESET_FULL_CHIP': ('E', 6),
    'LATCH_CLK_DATA': ('E', 7),
    'SERIAL_CHAIN_SEL1': ('C', 4),
    'PICI2C_RESET': ('C', 14),
}

DAC_CH = {
    'PLANE_VPP': 0,
    'DAC_VREF_ARRAY': 1,
    'P_VREF_TIA': 2,
    'DAC_VREF_HI_CMP': 3,
    'P_VREF_SH': 4,
    'DAC_VP_PAD': 5,
    'P_TVDD': 6,
    'P_VAGC_0': 7,
    'P_VAGC_1': 8,
    'P_ADC_EXT_TEST_IN': 9,
    'P_AMP_VREF': 10,
    'P_AMP_INPUT': 11,
    'DAC_SPARE1': 12,
    'DAC_SPARE2': 13,
    'DAC_DRIVE_VN': 14,
    'DAC_SCHOTTKY': 15,
}

DAC_SPAN = {
    0b000:  (0, 5),
    0b001:  (0, 10),
    0b010:  (-5, 5),
    0b011:  (-10, 10),
    0b100:  (-2.5, 2.5),
}

REFCLKO = {
    'CK_ARRAY': 0,  # REFCLKO1
    'ADC_CK':   2,  # REFCLKO3
}
