PIC_PINS = {
    'PIC_RESET_ROW_N'   : ('G', 1), 
    'PIC_RESET_COL_N'   : ('G', 0),
    'PIC_RESET_GLOBAL_N': ('E', 6),
    'PIC_STROBE_REG_N'  : ('B', 8),
    'PIC_RESET_DELAY_N' : ('B', 7),
    'PIC_ASSERT_COL'    : ('G', 12),
    'PIC_ASSERT_ND'     : ('G', 13),
    'PIC_ASSERT_REGS'   : ('G', 7),
    'PIC_ASSERT_CD'     : ('E', 0),
    'PIC_ASSERT_ML'     : ('F', 1),
    'PIC_ASSERT_WL'     : ('B', 11),
    'PIC_TCAM_TIA_SH_STRB'  : ('G', 8),
    'PIC_PC'            : ('B', 10),
    'DAC_LDAC_N'        : ('D', 0),
    'DAC_TGP'           : ('D', 12),
    'DAC_CLR_N'         : ('D', 9),
    'ADC_CONVST'        : ('E', 1),
    'ADC_EOC_N'         : ('A', 14),
    'ADC_CS_N'          : ('A', 9),
    'PIC_SA_LATCH'      : ('E', 7),
    'PIC_TRIGGER'       : ('E', 4),
    # TEMP
    'ADC_RD_N'          : ('K', 2),
    'ADC_WR_N'          : ('K', 1),
}

DAC_CH = {
    'ND': 0,
    'NS': 1,
    'WL': 2,
    'SL': 3,
    'SX': 4,
    'CD': 5,
    'ML_Z5': 6,
    'SA_REF': 7,
    'PC': 8,
    'PU': 9,
    'PRECHARGE': 10,
    'PUNY': 11,
    'PULSE': 12,
    'VCOL_REF_TIA': 13,
    'V_SH_OUTDRVR': 14,
    'SPARE': 15,
}
